export const QeustionData =[
    {
        id:1,
        title: "새로운 고양이를 데려왔다! 나의 반응은?",
        answera: "이름은 뭐라고 해줄까? 뭐하고 있어? 자꾸 말을 걸고 싶다",
        answerb: "혼자만의 시간이 필요하지? 적응할 시간을 준다",
        type: "EI",
    },
    {
        id:2,
        title: "고양이에 대한 모든 것이 궁금해졌다. 나의 행동은?",
        answera: "고양이 관련 커뮤니티에 들어 다른 집사님들과 소통을 하며 고양이에 대한 지식을 쌓는다.",
        answerb: "커뮤니티에 가입은 하지만 눈으로 참고만 하고 혼자 찾아보는게 편하다.",
        type: "EI",
    },
    {
        id:3,
        title: "",
        answera: "",
        answerb: "",
        type: "PJ",
    },
    {
        id:4,
        title: "",
        answera: "",
        answerb: "",
        type: "SN",
    },
    {
        id:5,
        title: "",
        answera: "",
        answerb: "",
        type: "SN",
    },
    {
        id:6,
        title: "",
        answera: " \"어떻게 지었을까? \" 고민한다.",
        answerb: " \"와.. 멋지다 \" 라고 감탄한다.",
        type: "SN",
    },
    {
        id:7,
        title: " 아침에 늦잠 잔 친구에게",
        answera: "여행이 역시 피곤하지",
        answerb: "내일은 시간 지키자",
        type: "FT",
    },
    {
        id:8,
        title: "친구에게 차 사고가 났다고 전화 왔을 때 나의 대답은?",
        answera: "\"괜찮아? 다친 데는 없어?\"라고 말하기",
        answerb: "\"보험은 들었어?\"라고 말하기",
        type: "FT",
    },
    {
        id:9,
        title: "친구가 쓸데없는 기념품을 살 때",
        answera: "니가 맘에 들면 사야지..",
        answerb: "니가 맘에 들면 사야지..",
        type: "FT",
    },
    {
        id:10,
        title: "나는 여행지를 선택할 때 주로 ",
        answera: "사람이 많은 도시로",
        answerb: "나무가 많은 자연으로",
        type: "EI",
    },
    {
        id:11,
        title: "숙소를 구할 때",
        answera: "저녁에 바베큐 파티를 여는 곳",
        answerb: "조용하고 아늑한 곳",
        type: "EI",
    },
    {
        id:12,
        title: "여행지에 대한 감상을",
        answera: "말로 내뱉어야 직성에 풀린다",
        answerb: "마음에 담고 느낀다. ",
        type: "EI",
    },
]


